#!/usr/bin/env node
/**
 * Bootstraps a new project from this template:
 * - Creates a Sanity project + dataset
 * - Creates an API token
 * - Adds localhost CORS
 * - Writes .env.local
 * - Seeds singleton documents
 *
 * Usage:
 *   pnpm bootstrap
 *   pnpm bootstrap --name "Cliente X" --org <orgId> --dataset production
 *
 * Note: do not use `pnpm setup` — that is a built-in pnpm PATH command.
 */

import { spawnSync } from "node:child_process";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import readline from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";

const ROOT = process.cwd();
const ENV_PATH = path.join(ROOT, ".env.local");
const PACKAGE_JSON_PATH = path.join(ROOT, "package.json");
const SANITY_CONFIG_PATH = path.join(ROOT, "sanity.config.ts");

/** Parsea flags CLI tipo --name=X o --force en un objeto { name: "X", force: "true" }. */
function parseArgs(argv) {
  const flags = {};
  for (const arg of argv) {
    if (!arg.startsWith("--")) continue;
    const [key, ...rest] = arg.slice(2).split("=");
    flags[key] = rest.length ? rest.join("=") : "true";
  }
  return flags;
}

/**
 * Ejecuta un comando del sistema y captura stdout/stderr.
 * Si allowFail es false y el exit code ≠ 0, lanza Error.
 */
function run(command, args, { allowFail = false, env } = {}) {
  const result = spawnSync(command, args, {
    cwd: ROOT,
    encoding: "utf8",
    env: { ...process.env, ...env },
    stdio: ["inherit", "pipe", "pipe"],
  });

  if (result.error) {
    throw result.error;
  }

  if (result.status !== 0 && !allowFail) {
    const stderr = (result.stderr || "").trim();
    const stdout = (result.stdout || "").trim();
    throw new Error(
      [`Command failed: ${command} ${args.join(" ")}`, stderr || stdout]
        .filter(Boolean)
        .join("\n"),
    );
  }

  return {
    status: result.status ?? 1,
    stdout: result.stdout || "",
    stderr: result.stderr || "",
  };
}

/** Atajo para correr `pnpm exec sanity <args>` vía `run`. */
function sanity(args, options) {
  return run("pnpm", ["exec", "sanity", ...args], options);
}

/**
 * Extrae un objeto JSON del stdout/stderr del CLI.
 * Útil porque Sanity a veces imprime spinners/texto junto al JSON.
 */
function extractJson(text) {
  const trimmed = text.trim();
  if (!trimmed) return null;

  try {
    return JSON.parse(trimmed);
  } catch {
    const start = trimmed.indexOf("{");
    const end = trimmed.lastIndexOf("}");
    if (start === -1 || end === -1 || end < start) return null;
    try {
      return JSON.parse(trimmed.slice(start, end + 1));
    } catch {
      return null;
    }
  }
}

/** Convierte un nombre de proyecto a slug válido para package.json (ej. "Cliente X" → "cliente-x"). */
function slugify(value) {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 64);
}

/** Escribe `.env.local` con project id, dataset, token y secrets del proyecto nuevo. */
function writeEnvLocal({
  projectId,
  dataset,
  token,
  siteUrl,
  revalidateSecret,
}) {
  const contents = `# Generated by pnpm bootstrap — do not commit
NEXT_PUBLIC_SANITY_PROJECT_ID="${projectId}"
NEXT_PUBLIC_SANITY_DATASET="${dataset}"
SANITY_API_TOKEN="${token}"

NEXT_PUBLIC_SITE_URL="${siteUrl}"
NEXT_PUBLIC_IS_LIVE="development"

SANITY_REVALIDATE_SECRET="${revalidateSecret}"
`;

  fs.writeFileSync(ENV_PATH, contents, "utf8");
  console.log(`\n  ✓ Wrote ${path.relative(ROOT, ENV_PATH)}`);
}

/** Renombra el campo `name` de package.json al slug del proyecto. */
function updatePackageName(projectName) {
  const pkg = JSON.parse(fs.readFileSync(PACKAGE_JSON_PATH, "utf8"));
  pkg.name = slugify(projectName) || pkg.name;
  fs.writeFileSync(PACKAGE_JSON_PATH, `${JSON.stringify(pkg, null, 2)}\n`, "utf8");
  console.log(`  ✓ package.json name → ${pkg.name}`);
}

/** Actualiza el `title` del Studio en sanity.config.ts (ej. "Cliente X CMS"). */
function updateStudioTitle(projectName) {
  if (!fs.existsSync(SANITY_CONFIG_PATH)) return;

  const source = fs.readFileSync(SANITY_CONFIG_PATH, "utf8");
  const next = source.replace(
    /title:\s*['"][^'"]*['"]/,
    `title: '${projectName.replace(/'/g, "\\'")} CMS'`,
  );

  if (next !== source) {
    fs.writeFileSync(SANITY_CONFIG_PATH, next, "utf8");
    console.log(`  ✓ sanity.config.ts title → ${projectName} CMS`);
  }
}

/**
 * Completa lo que falte: pide por terminal name/org/dataset/siteUrl
 * si no vinieron como flags (--name, --org, etc.).
 */
async function promptMissing(flags) {
  const rl = readline.createInterface({ input, output });

  try {
    const name =
      flags.name ||
      (await rl.question("Project name (e.g. Cliente X): ")).trim();

    if (!name) {
      throw new Error("Project name is required.");
    }

    const org =
      flags.org ||
      (
        await rl.question(
          "Sanity organization id/slug (optional, Enter to skip): ",
        )
      ).trim();

    const dataset =
      flags.dataset ||
      (await rl.question("Dataset name [production]: ")).trim() ||
      "production";

    const siteUrl =
      flags["site-url"] ||
      (await rl.question("Site URL [http://localhost:3000]: ")).trim() ||
      "http://localhost:3000";

    const skipSingletons = flags["skip-singletons"] === "true";

    return { name, org, dataset, siteUrl, skipSingletons };
  } finally {
    rl.close();
  }
}

/**
 * Verifica que el usuario esté logueado en Sanity CLI.
 * Si `projects list` falla, abre el flujo de `sanity login`.
 */
function ensureSanityLogin() {
  const list = sanity(["projects", "list"], { allowFail: true });
  if (list.status === 0) return;

  console.log("\nYou need to log in to Sanity first.\n");
  const login = spawnSync("pnpm", ["exec", "sanity", "login"], {
    cwd: ROOT,
    stdio: "inherit",
  });
  if (login.status !== 0) {
    throw new Error("Sanity login failed. Run `pnpm exec sanity login` and retry.");
  }
}

/**
 * Crea un proyecto Sanity nuevo + dataset vía CLI.
 * Devuelve { projectId, dataset } parseando el JSON de salida.
 */
function createProject({ name, org, dataset }) {
  const args = [
    "projects",
    "create",
    name,
    "--dataset",
    dataset,
    "--dataset-visibility",
    "public",
    "--json",
    "--yes",
  ];

  if (org) {
    args.push("--organization", org);
  }

  console.log("\n→ Creating Sanity project…");
  const result = sanity(args);
  const data = extractJson(result.stdout) || extractJson(result.stderr);

  // `sanity projects create --json` prints the project object only (projectId, displayName, …)
  const projectId = data?.projectId || data?.id;
  if (!projectId) {
    throw new Error(
      `Could not parse project create output.\n${result.stdout}\n${result.stderr}`,
    );
  }

  console.log(`  ✓ Project: ${projectId}`);
  console.log(`  ✓ Dataset: ${dataset}`);

  return { projectId, dataset };
}

/**
 * Crea un API token con rol viewer (solo lectura).
 * Suficiente para SanityLive, draft mode y leer drafts — no necesita write.
 * Devuelve el secret `sk...` (solo se muestra una vez).
 */
function createToken(projectId) {
  console.log("\n→ Creating API token (viewer)…");
  const result = sanity([
    "tokens",
    "add",
    "Local Dev",
    "--role",
    "viewer",
    "--project-id",
    projectId,
    "--json",
    "--yes",
  ]);

  const data = extractJson(result.stdout) || extractJson(result.stderr);
  const token = data?.key;

  if (!token || typeof token !== "string") {
    const match = `${result.stdout}\n${result.stderr}`.match(
      /sk[A-Za-z0-9]{20,}/,
    );
    if (match) {
      console.log("  ✓ Token created");
      return match[0];
    }
    throw new Error(
      `Could not parse API token from output.\n${result.stdout}\n${result.stderr}`,
    );
  }

  console.log("  ✓ Token created");
  return token;
}

/**
 * Registra el origin del sitio (ej. http://localhost:3000) en CORS del proyecto,
 * necesario para que el Studio embebido pueda autenticarse.
 */
function addCors(projectId, siteUrl) {
  const origin = siteUrl.replace(/\/$/, "");
  console.log(`\n→ Adding CORS origin ${origin}…`);
  sanity([
    "cors",
    "add",
    origin,
    "--credentials",
    "--project-id",
    projectId,
  ], { allowFail: true });
  console.log("  ✓ CORS configured (or already present)");
}

/**
 * Siembra los documentos singleton (home, header, footer) definidos en config/singletons.
 * Usa el token de usuario de Sanity CLI (--with-user-token).
 */
function seedSingletons() {
  console.log("\n→ Seeding singleton documents…");
  const result = spawnSync(
    "pnpm",
    ["exec", "sanity", "exec", "./scripts/createSingletons.mjs", "--with-user-token"],
    { cwd: ROOT, stdio: "inherit", env: process.env },
  );

  if (result.status !== 0) {
    console.warn(
      "  ⚠ Singletons seeding failed. Run `pnpm create:singletons` later.",
    );
    return;
  }

  console.log("  ✓ Singletons created");
}

/**
 * Orquesta todo el bootstrap en orden:
 * prompts → login → proyecto → token → CORS → .env.local → rename → singletons.
 */
async function main() {
  const flags = parseArgs(process.argv.slice(2));

  console.log("\nENLACE boilerplate setup\n");

  if (fs.existsSync(ENV_PATH) && flags.force !== "true") {
    console.log(
      `.env.local already exists. Re-run with --force to overwrite, or delete it first.`,
    );
    process.exit(1);
  }

  const answers = await promptMissing(flags);
  ensureSanityLogin();

  const { projectId, dataset } = createProject(answers);
  const token = createToken(projectId);
  addCors(projectId, answers.siteUrl);

  const revalidateSecret = crypto.randomBytes(24).toString("hex");
  writeEnvLocal({
    projectId,
    dataset,
    token,
    siteUrl: answers.siteUrl.replace(/\/$/, ""),
    revalidateSecret,
  });

  updatePackageName(answers.name);
  updateStudioTitle(answers.name);

  // Ensure subsequent sanity CLI commands read the new env
  process.env.NEXT_PUBLIC_SANITY_PROJECT_ID = projectId;
  process.env.NEXT_PUBLIC_SANITY_DATASET = dataset;
  process.env.SANITY_API_TOKEN = token;

  if (!answers.skipSingletons) {
    seedSingletons();
  }

  console.log(`
Done.

Next steps:
  1. pnpm install   (if you haven't already)
  2. pnpm dev
  3. Open http://localhost:3000/studio

Useful commands:
  pnpm new:section <name>
  pnpm create:singletons
`);
}

main().catch((error) => {
  console.error(`\nSetup failed:\n${error.message}\n`);
  process.exit(1);
});
